import { DM_Sans, Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dmSans.variable} ${inter.variable}`}>
      <body className="antialiased bg-color-background">
        <div id="root">{children}</div>
        <footer className="bg-foreground-50 text-foreground-100 flex justify-center text-sm py-3 border-t-1 border-foreground-100 w-screen">
          @2025 All Rights Reserved | Elevate your brand
        </footer>
      </body>
    </html>
  );
}
