import { DM_Sans, Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const font = DM_Sans({
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}>
      <body className="antialiased bg-color-background">{children}</body>
    </html>
  );
}
